version: '3'

services:
  taxi-server:
    build:
      context: .
    container_name: taxi-server
    command: >
      sh -c "python manage.py migrate &&
             daphne --bind 0.0.0.0 --port 8000 taxi.asgi:application"
    depends_on:
      - taxi-redis
      - taxi-database
    env_file: 
      - ./.env
    ports:
      - '8001:8000'
    volumes:
      - ./server:/server
      - media:/server/media
      - static:/server/static

  taxi-database:
    container_name: taxi-database
    image: postgres:10-alpine
    env_file: 
      - ./.env
    ports:
      - '5433:5432'
    volumes:
      - taxi-database:/var/lib/postgresql/data

  taxi-redis:
    container_name: taxi-redis
    image: redis
  
  taxi-client:
    build:
      context: ./client
    command: ng serve --host 0.0.0.0
    container_name: taxi-client
    depends_on:
      - taxi-server
    environment:
      - CHROME_BIN=chromium-browser
    ports:
      - 4201:4200
    volumes:
      - ./client:/usr/src/app

  nginx:
    build:
      context: ./nginx
    container_name: taxi-nginx
    depends_on: 
      - taxi-server
      - taxi-client
    ports:
      - 8084:80
    restart: always
    volumes: 
      - media:/server/media
      - static:/server/static

volumes:
  taxi-database:
  media:
  static:
